### ISSUE TITLE
Using a list of bitarrays with sklearn

### ISSUE THREAD

**Issue by tapadeep** [ilanschnell/bitarray#148]
I have a huge binary dataset which I'm reading into a list of bitarrays (each bitarray represents an instance). Now I want to use sklearn's simple linear classifiers on the data for making output predictions. Presently I'm using the following code to convert the list of bitarrays to a list of lists to bring it into a form that sklearn can recognize:

`for i in range(n):
    X[i]=X[i].tolist()`

Needless to say, the memory explodes, is there any smarter way of achieving this?

**Comment by ilanschnell** [comment]
Your code for converting a list to bitarrays to a list of lists looks fine.  The problem is that when converting each bitarray `X[i]` to a list, it will use 64 times more memory (as a single bit in a list is stored as a 64-bit pointer.  I'm assuming you're using a 64-bit system).  I'm not sure what sklearn functionality you're using, but perhaps there is the ability to use another data structure sklearn can recognize.  For example, you use a numpy array with `dtype=bool`, this would still use 1 byte per bit, but a factor of 8 is better than a factor of 64.  Maybe there is also the possibility to process each bitarray `X[i]` at a time, such that not all of the bitarrays `X` need to be unpacked at once.

**Comment by tapadeep** [comment]
Yes, a byte-sized numpy array would be better. How do I go from bitarray to boolean numpy array?

**Comment by tapadeep** [comment]
> Your code for converting a list to bitarrays to a list of lists looks fine. The problem is that when converting each bitarray `X[i]` to a list, it will use 64 times more memory (as a single bit in a list is stored as a 64-bit pointer. I'm assuming you're using a 64-bit system). I'm not sure what sklearn functionality you're using, but perhaps there is the ability to use another data structure sklearn can recognize. For example, you use a numpy array with `dtype=bool`, this would still use 1 byte per bit, but a factor of 8 is better than a factor of 64. Maybe there is also the possibility to process each bitarray `X[i]` at a time, such that not all of the bitarrays `X` need to be unpacked at once.

**Comment by ilanschnell** [comment]
There is an example how binary data can be efficiently be passed between a bitarray object and an ndarray with dtype bool: https://github.com/ilanschnell/bitarray/blob/master/examples/ndarray.py
