### ISSUE TITLE
Feature: frombytes() and fromfile() should return the bitarray object.

### ISSUE THREAD

**Issue by admoore2016** [ilanschnell/bitarray#158]
When writing code that goes back and forth between bitarrays and byte-like objects, it would be very helpful to return the bitarray object when initializing using these functions. Currently if you want to create and initialize a bitarray, you need to do:

```
b = bitarray()
b.frombytes(...)
```

whereas, if the object was returned, you could simply write the following:

```
b = bitarray().frombytes(...)
```

**Comment by ilanschnell** [comment]
Thanks for using bitarray and raising this issue.  The `.frombytes()` (as well as other) method(s), have been designed to behave like the corresponding methods of Python's standard library `array` object.  The `array` module (as well as the `list` object) have guided the interface in order to avoid yet other method names and behavior.  If your code uses `.frombytes()` (on a new bitarray) a lot, you can always create a function for this usecase.

**Comment by admoore2016** [comment]
Thanks for getting back to me so fast. I think for now I'll do as you suggest and make my own function for that use case. In the future when I have more time, I might consider making a pull request adding something like `bytes2ba()` in `bitarray.util`, but for now I'll close this issue.
